#!/bin/bash
# Railway Deployment Command Reference
# Save this file as reference_commands.sh

echo "🚀 Hexaglass Backend - Railway Deployment Commands"
echo ""
echo "=== LOCAL TESTING ==="
echo "composer install          # Install PHP dependencies"
echo "npm install               # Install Node dependencies"
echo "npm run build             # Build assets"
echo "php artisan serve         # Run local development server"
echo "php artisan migrate       # Run database migrations"
echo "php artisan db:seed       # Seed database (if seeders exist)"
echo ""
echo "=== GIT & GITHUB ==="
echo "git add .                 # Stage all changes"
echo "git commit -m 'message'   # Commit changes"
echo "git push origin main      # Push to GitHub"
echo ""
echo "=== RAILWAY COMMANDS ==="
echo "railway exec bash         # SSH into deployed app"
echo "railway logs              # View application logs"
echo "railway env list          # List environment variables"
echo "railway metrics            # View app metrics"
echo ""
echo "=== PRODUCTION MANAGEMENT (SSH) ==="
echo "php artisan migrate       # Run migrations"
echo "php artisan logs          # View application logs"
echo "php artisan db:show       # Show database info"
echo "php artisan cache:clear   # Clear cache"
echo "php artisan config:clear  # Clear config cache"
echo "php artisan tinker        # PHP REPL"
echo "php artisan db:table      # List database tables"
echo ""
echo "=== TROUBLESHOOTING ==="
echo "chmod -R 755 storage/     # Fix storage permissions"
echo "chmod -R 755 bootstrap/cache/"
echo "php artisan config:cache  # Cache config for production"
echo "php artisan route:cache   # Cache routes for production"
echo "php artisan view:cache    # Cache views for production"
echo ""
echo "=== EMAIL TESTING ==="
echo "php artisan tinker"
echo ">>> use Illuminate\\Support\\Facades\\Mail;"
echo ">>> Mail::to('test@example.com')->send(new TestMail());"
echo ""
echo "=== QUEUE TESTING ==="
echo "php artisan queue:work    # Start queue worker"
echo "php artisan queue:failed  # List failed jobs"
echo "php artisan queue:flush   # Clear queue"
echo ""
echo "✅ For detailed instructions, see:"
echo "   - QUICK_START.md"
echo "   - RAILWAY_DEPLOYMENT.md"
echo "   - DEPLOYMENT_CHECKLIST.md"
